const IMAGE_URL="https://static.wixstatic.com/media/6d9e77_6f12e24e96e146978e49d51017278897~mv2.jpg/v1/fill/w_1800,h_2100,al_c,q_95,enc_avif,quality_auto/6d9e77_6f12e24e96e146978e49d51017278897~mv2.webp";
const STORAGE_KEY="ielts-pabs-writing-academic-16-test-2-preview-v4";
const tasks={
1:{title:"Writing Task 1",html:`<p>You should spend about 20 minutes on this task.</p><div class="task-question"><p>The diagram below shows the manufacturing process for making sugar from sugar cane.</p><p>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</p></div><p>Write at least 150 words.</p><figure class="task-visual"><div class="visual-frame"><img id="taskImage" src="${IMAGE_URL}" alt="A seven-stage process showing how sugar is produced from sugar cane, from growing and harvesting to drying and cooling." tabindex="0" title="Click to enlarge the diagram within this pane"></div></figure>`,study:{type:"Process diagram",understanding:["Describe the stages in a clear sequence.","Include an overview of the whole process.","Report the main features without giving an opinion."],structure:["Introduction","Overview","Early stages: growing, harvesting and crushing","Later stages: purification, evaporation, separation, drying and cooling"],checklist:["I included a clear overview.","I described the stages in a logical order.","I used accurate process language.","I wrote at least 150 words."]}},
2:{title:"Writing Task 2",html:`<p>You should spend about 40 minutes on this task.</p><p>Write about the following topic:</p><div class="task-question"><p>In their advertising, businesses nowadays usually emphasise that their products are new in some way.</p><p>Why is this? Do you think it is a positive or negative development?</p></div><p>Give reasons for your answer and include any relevant examples from your own knowledge or experience.</p><p>Write at least 250 words.</p>`,study:{type:"Two-part question",understanding:["Explain why businesses emphasise that products are new.","Answer whether this is a positive or negative development.","Keep your position clear throughout the essay."],structure:["Introduction","Why businesses emphasise novelty","Evaluation of the development","Conclusion"],checklist:["I answered both questions.","My position is clear.","Each main idea is explained and supported.","I wrote at least 250 words."]}}
};
const $=id=>document.getElementById(id);
let state={mode:null,task:1,answers:{1:"",2:""},candidate:"",deadline:null,submitted:false,split:50,theme:"black-on-white",font:"normal"};
let timerId=null,saveId=null,dragging=false,timerPaused=false,fullscreenEnforced=false;
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null");if(saved)state={...state,...saved,answers:{...state.answers,...saved.answers}}}catch(error){}}
function saveState(show=true){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(show&&$("saveStatus"))$("saveStatus").textContent="Saved locally"}
function scheduleSave(){clearTimeout(saveId);$("saveStatus").textContent="Saving…";saveId=setTimeout(()=>saveState(true),300)}
function countWords(text){return(text.trim().match(/[A-Za-z0-9]+(?:['’][A-Za-z0-9]+)*(?:-[A-Za-z0-9]+)*/g)||[]).length}
function updateWordCount(){$("wordCount").textContent="Words: "+countWords($("answerEditor").value)}
function syncAnswer(){state.answers[state.task]=$("answerEditor").value}
function chooseMode(mode){if(mode==="test"){$("testStartScreen").style.display="block";$("studentNameInput").focus()}else startAttempt("study")}
async function beginTimedTest(){const name=$("studentNameInput").value.trim();if(!name){alert("Please enter your name before starting test mode.");$("studentNameInput").focus();return}state.candidate=name;fullscreenEnforced=false;if(isFullscreenSupported())fullscreenEnforced=await requestFullscreen();else $("fullscreenSupportNote").style.display="block";startAttempt("test")}
function startAttempt(mode){state.mode=mode;state.task=1;state.submitted=false;state.deadline=mode==="test"?Date.now()+3600000:null;saveState(false);$("modeScreen").style.display="none";$("app").style.display="block";renderChrome();renderTask();startTimer();$("answerEditor").focus()}
function renderChrome(){const study=state.mode==="study";$("studyHeaderChrome").style.display=study?"flex":"none";$("timerContainer").style.display=state.mode==="test"?"block":"none";$("candidateNameDisplay").style.display=state.mode==="test"&&state.candidate?"block":"none";$("candidateNameDisplay").textContent=state.candidate?"Candidate: "+state.candidate:"";$("optionsSubmit").style.display=state.mode==="test"&&!state.submitted?"flex":"none";$("submittedBanner").style.display=state.submitted?"block":"none";document.body.dataset.theme=state.theme||"black-on-white";document.body.classList.toggle("font-large",state.font==="large");document.body.classList.toggle("font-xlarge",state.font==="xlarge");document.documentElement.style.setProperty("--split",(state.split||50)+"%");updateOptionButtons();updateFullscreenButton()}
function renderTask(){const task=tasks[state.task];$("taskHeader").textContent=task.title;$("taskCopy").innerHTML=task.html;$("answerEditor").value=state.answers[state.task]||"";$("answerEditor").disabled=!!state.submitted;$("passagePane").classList.remove("image-focus");document.querySelectorAll(".part-chip").forEach(chip=>chip.classList.toggle("active",Number(chip.dataset.task)===state.task));$("prevTask").disabled=state.task===1;$("nextTask").disabled=state.task===2;$("submitButton").title=state.mode==="test"?"Submit test":"Self-review";$("submitButton").setAttribute("aria-label",$("submitButton").title);updateWordCount();wireImage()}
function switchTask(number){if(!tasks[number])return;syncAnswer();state.task=number;saveState(false);renderTask();$("answerEditor").focus()}
function wireImage(){const image=$("taskImage");if(!image)return;const toggle=()=>$("passagePane").classList.toggle("image-focus");image.addEventListener("click",toggle);image.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();toggle()}})}
function startTimer(){clearInterval(timerId);if(state.mode!=="test"||state.submitted)return;const draw=()=>{const left=Math.max(0,Math.ceil((state.deadline-Date.now())/1000));$("timerDisplay").textContent=String(Math.floor(left/60)).padStart(2,"0")+":"+String(left%60).padStart(2,"0");$("timerDisplay").classList.toggle("timer-warning",left<=180);if(left<=0)submitTest("time")};draw();timerId=setInterval(draw,1000)}
function pauseTimer(){clearInterval(timerId);timerId=null;timerPaused=true}
function resumeTimer(){if(timerPaused&&state.mode==="test"&&!state.submitted){timerPaused=false;startTimer()}}
function openSubmit(){syncAnswer();$("submitSummary").textContent=`Writing Task 1: ${countWords(state.answers[1]||"")} words. Writing Task 2: ${countWords(state.answers[2]||"")} words. Your answers will be locked after submission.`;$("submitOverlay").style.display="flex"}
function submitTest(reason="student"){syncAnswer();state.submitted=true;state.submissionReason=reason;saveState(false);clearInterval(timerId);$("submitOverlay").style.display="none";renderChrome();renderTask()}
function openSelfReview(){const items=tasks[state.task].study.checklist.map(item=>`<li>${item}</li>`).join("");$("reviewContent").innerHTML=`<ul>${items}</ul>`;$("reviewOverlay").style.display="flex"}
function openStudyTools(){const s=tasks[state.task].study;const list=(heading,items,ordered=false)=>`<section><h3>${heading}</h3><${ordered?"ol":"ul"}>${items.map(item=>`<li>${item}</li>`).join("")}</${ordered?"ol":"ul"}></section>`;$("studyDrawerBody").innerHTML=`<section><h3>Task type</h3><p>${s.type}</p></section>`+list("Understanding the question",s.understanding)+list("Suggested structure",s.structure,true)+list("Self-review checklist",s.checklist);$("studyDrawer").hidden=false}
function openOptions(show){$("optionsOverlay").style.display=show?"flex":"none"}
function setTheme(theme){state.theme=theme;saveState(false);renderChrome()}
function setFont(font){state.font=font;saveState(false);renderChrome()}
function updateOptionButtons(){document.querySelectorAll("[data-theme-choice]").forEach(button=>button.classList.toggle("active",button.dataset.themeChoice===state.theme));document.querySelectorAll("[data-font-choice]").forEach(button=>button.classList.toggle("active",button.dataset.fontChoice===state.font))}
function isFullscreenSupported(){return!!(document.fullscreenEnabled&&document.documentElement.requestFullscreen)}
function isFullscreenActive(){return!!document.fullscreenElement}
async function requestFullscreen(){try{await document.documentElement.requestFullscreen();return isFullscreenActive()}catch(error){return false}}
async function exitFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen()}catch(error){}}
async function toggleFullscreen(){if(state.mode==="test"&&!state.submitted&&fullscreenEnforced&&isFullscreenActive())return;if(isFullscreenActive())await exitFullscreen();else await requestFullscreen();updateFullscreenButton()}
function updateFullscreenButton(){const locked=state.mode==="test"&&!state.submitted&&fullscreenEnforced&&isFullscreenActive();$("fullscreenBtn").classList.toggle("is-active",isFullscreenActive());$("fullscreenBtn").disabled=locked;$("fullscreenBtnLabel").textContent=locked?"Full screen locked":isFullscreenActive()?"Exit full screen":"Full screen"}
function handleFullscreenChange(){if(state.mode==="test"&&!state.submitted&&fullscreenEnforced){if(!isFullscreenActive()){pauseTimer();$("fullscreenLockOverlay").style.display="flex"}else{$("fullscreenLockOverlay").style.display="none";resumeTimer()}}updateFullscreenButton()}
async function returnToFullscreen(){if(await requestFullscreen()){$("fullscreenLockOverlay").style.display="none";resumeTimer()}updateFullscreenButton()}
function confirmHome(){if(state.mode&&!state.submitted&&!confirm("Leave this Writing test and return to the hub? Your saved work will remain on this device."))return;window.location.href="../../index.html"}
function setupDivider(){const divider=$("divider");divider.addEventListener("pointerdown",event=>{dragging=true;divider.setPointerCapture?.(event.pointerId)});divider.addEventListener("pointermove",event=>{if(!dragging)return;const rect=$("mainInner").getBoundingClientRect();state.split=Math.max(28,Math.min(72,(event.clientX-rect.left)/rect.width*100));document.documentElement.style.setProperty("--split",state.split+"%")});divider.addEventListener("pointerup",()=>{dragging=false;saveState(false)});divider.addEventListener("keydown",event=>{if(event.key!=="ArrowLeft"&&event.key!=="ArrowRight")return;state.split=Math.max(28,Math.min(72,state.split+(event.key==="ArrowRight"?2:-2)));document.documentElement.style.setProperty("--split",state.split+"%");saveState(false)})}
document.querySelectorAll(".mode-btn[data-mode]").forEach(button=>button.addEventListener("click",()=>chooseMode(button.dataset.mode)));
$("beginTestBtn").addEventListener("click",beginTimedTest);$("answerEditor").addEventListener("input",()=>{syncAnswer();updateWordCount();scheduleSave()});document.querySelectorAll(".part-chip").forEach(chip=>chip.addEventListener("click",()=>switchTask(Number(chip.dataset.task))));$("prevTask").addEventListener("click",()=>switchTask(1));$("nextTask").addEventListener("click",()=>switchTask(2));$("submitButton").addEventListener("click",()=>state.mode==="test"?openSubmit():openSelfReview());$("optionsBtn").addEventListener("click",()=>openOptions(true));$("optionsClose").addEventListener("click",()=>openOptions(false));$("optionsOverlay").addEventListener("click",event=>{if(event.target===$("optionsOverlay"))openOptions(false)});$("optionsSubmit").addEventListener("click",()=>{openOptions(false);openSubmit()});$("cancelSubmit").addEventListener("click",()=>$("submitOverlay").style.display="none");$("confirmSubmit").addEventListener("click",()=>submitTest("student"));$("closeReview").addEventListener("click",()=>$("reviewOverlay").style.display="none");$("studyToolsBtn").addEventListener("click",openStudyTools);$("closeStudyDrawer").addEventListener("click",()=>$("studyDrawer").hidden=true);$("fullscreenBtn").addEventListener("click",toggleFullscreen);$("returnFullscreenBtn").addEventListener("click",returnToFullscreen);$("homeLogo").addEventListener("click",confirmHome);document.querySelectorAll("[data-theme-choice]").forEach(button=>button.addEventListener("click",()=>setTheme(button.dataset.themeChoice)));document.querySelectorAll("[data-font-choice]").forEach(button=>button.addEventListener("click",()=>setFont(button.dataset.fontChoice)));document.addEventListener("fullscreenchange",handleFullscreenChange);window.addEventListener("beforeunload",event=>{if(state.mode&&!state.submitted){syncAnswer();saveState(false);event.preventDefault();event.returnValue=""}});setupDivider();loadState();if(state.mode){$("modeScreen").style.display="none";$("app").style.display="block";renderChrome();renderTask();startTimer()}else $("modeScreen").style.display="flex";